version: '3.4'

services:
  customerservice:
    image: ${DOCKER_REGISTRY-}customerservice
    container_name: customerservice
    depends_on:
      - elasticsearch
    build:
      context: .
      dockerfile: Services/CustomerService/Dockerfile

  orderservice:
    image: ${DOCKER_REGISTRY-}orderservice
    depends_on:
      - elasticsearch
    container_name: orderservice
    build:
      context: .
      dockerfile: Services/OrderService/Dockerfile


  gateway:
    image: ${DOCKER_REGISTRY-}gateway
    container_name: gateway
    build:
      context: .
      dockerfile: Services/Gateway/Dockerfile


  elasticsearch:
    image: elasticsearch:7.14.1
    container_name: elasticsearch
      
  kibana:
    image: kibana:7.14.1
    container_name: kibana




volumes:
  elasticsearch-data:
    driver: local
networks:
  docker-network:
    driver: bridge
